### ISSUE TITLE
Maybe array typo

### ISSUE THREAD

**Issue by GuepardoApps** [AndreaCioccarelli/CryptoPrefs#3]
I'm not sure about that, but I think you do have a typo in this [array](https://github.com/AndreaCioccarelli/CryptoPrefs/blob/f97f33ace54eea86e1d5d6185b187caf0000c679/library/src/main/java/com/andreacioccarelli/cryptoprefs/wrappers/PreferencesEncrypter.kt#L73). 
I think it should be "abcdefghijklmnopqrstuvwxyz123456789".

**Comment by AndreaCioccarelli** [comment]
Good catch.
