### ISSUE TITLE
Updating to kotlin 1.3 to add experimental support for unsigned  types

### ISSUE THREAD

**Issue by GuepardoApps** [AndreaCioccarelli/CryptoPrefs#5]
Kotlin 1.3 is now supporting [unsigned types](https://kotlinlang.org/docs/reference/whatsnew13.html). It is still experimental, but might be interesting. Do you want to have that in your library?
I added it in my [experimental branch](https://github.com/GuepardoApps/CryptoPrefs/tree/experimental)

**Comment by AndreaCioccarelli** [comment]
I think it may be kind of weird from a developer to really use it, but giving the user the biggest possible range of choices is always the best thing to do. Good idea :)
Any other type we're missing?

**Comment by GuepardoApps** [comment]
Wow, your implementation and refactoring was quick! 😄 
Kotlin provides lots of types. but beside the new unsigned types I don't think they should be added.

**Comment by AndreaCioccarelli** [comment]
Do you think that this may cause any problem from java usages? Because those classes doesn't exists there but to get a object of type `UInt` you need to pass a default argument that is `UInt`

**Comment by GuepardoApps** [comment]
Actually I did not think about that. But to get a type which only exists in Kotlin, but not in Java, first needs the save of such a type. And if you cannot load such a type you also cannot save it. So I would not worry about that.
It also seems supporting some kind of @Unsigned annotation is discussed (or already implemented, I don't know, sorry) to load from Java to Kotlin ([Source](https://github.com/Kotlin/KEEP/blob/master/proposals/unsigned-types.md) -> scroll to the bottom to Unresolved questions)

**Comment by AndreaCioccarelli** [comment]
Well, since they are still experimental is better to see what happens in the future.
In the making we provide support for them, because as mentioned earlier they won't cause issues
